import nextCoreWebVitals from 'eslint-config-next/core-web-vitals'
import nextTypescript from 'eslint-config-next/typescript'

/**
 * Flat config. `eslint-config-next` ships native flat configs from v16, so the
 * FlatCompat shim is no longer needed.
 */
const config = [
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'qa/**',
      'test-results/**',
      'playwright-report/**',
      // Generated by Payload; not ours to lint.
      'src/payload-types.ts',
      'src/app/(payload)/admin/importMap.js',
      // Generated by `payload migrate:create`. Hand-editing a migration that
      // has already run somewhere is how schemas drift, so these are read-only
      // in practice and the generator's style is not ours to argue with.
      'src/migrations/**',
    ],
  },
  ...nextCoreWebVitals,
  ...nextTypescript,
  {
    rules: {
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
]

export default config
