/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    categories: Category;
    authors: Author;
    'sourcing-categories': SourcingCategory;
    deliveries: Delivery;
    'aquarium-projects': AquariumProject;
    testimonials: Testimonial;
    faqs: Faq;
    enquiries: Enquiry;
    media: Media;
    'private-media': PrivateMedia;
    users: User;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    'sourcing-categories': SourcingCategoriesSelect<false> | SourcingCategoriesSelect<true>;
    deliveries: DeliveriesSelect<false> | DeliveriesSelect<true>;
    'aquarium-projects': AquariumProjectsSelect<false> | AquariumProjectsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'private-media': PrivateMediaSelect<false> | PrivateMediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    'site-settings': SiteSetting;
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Every public route. Build the page body from the layout blocks.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Policy pages render with a legal-document layout and a review notice.
   */
  pageType: 'standard' | 'policy' | 'utility';
  /**
   * Shows a visible notice on the page and blocks it from the sitemap until unticked.
   */
  legalReviewRequired?: boolean | null;
  /**
   * The opening of the page. Leave the heading blank to omit it.
   */
  hero?: {
    eyebrow?: string | null;
    /**
     * Defaults to the page title when blank.
     */
    heading?: string | null;
    intro?: string | null;
    image?: (number | null) | Media;
  };
  /**
   * Drag to reorder. Each block has its own "Hide this section" switch if you want to keep content without showing it.
   */
  layout?:
    | (
        | HeroBlock
        | SectionIntroBlock
        | RichTextBlock
        | MediaCopySplitBlock
        | ProcessRouteBlock
        | CategoryGridBlock
        | SpecimenRecordBlock
        | DeliveryStoriesBlock
        | AquariumFeatureBlock
        | ImageGalleryBlock
        | VideoBlock
        | TrustStatementsBlock
        | FeaturedArticlesBlock
        | FaqsBlock
        | CtaBlock
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Absolute URL. Only set this when the same content is also published somewhere else.
     */
    canonicalUrl?: string | null;
    /**
     * Adds noindex,nofollow and removes this page from the sitemap.
     */
    noIndex?: boolean | null;
  };
  /**
   * URL path segment. Generated from the title; edit to override.
   */
  slug: string;
  /**
   * Marks this page as a navigation candidate. The actual menu order is set in the Header global.
   */
  showInNavigation?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Public images and video used across the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Tick for images that carry no information. Assistive technology will ignore them and no alt text is needed.
   */
  decorative?: boolean | null;
  /**
   * Describe what the image shows and why it matters. Required for meaningful images.
   */
  alt?: string | null;
  /**
   * Shown under the image where supported.
   */
  caption?: string | null;
  credit?: string | null;
  /**
   * Free-form labels to help find this file later.
   */
  tags?: string[] | null;
  /**
   * Set by the seed script so re-seeding updates this file instead of uploading a duplicate. Leave blank for files you upload yourself.
   */
  seedKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    social?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * Keeps the content but removes the section from the public page.
   */
  hidden?: boolean | null;
  /**
   * Small label above the headline.
   */
  eyebrow?: string | null;
  /**
   * Use "*" around a word or phrase to emphasise it in Scarlet.
   */
  headline: string;
  /**
   * Two or three sentences at most.
   */
  body?: string | null;
  /**
   * Short reassurance under the CTAs.
   */
  trustLine?: string | null;
  primaryCta?: {
    /**
     * Button or link text.
     */
    label?: string | null;
    type?: ('internal' | 'external' | 'whatsapp') | null;
    /**
     * Path starting with "/" — for example /source-a-fish
     */
    href?: string | null;
    /**
     * Full URL including https://
     */
    url?: string | null;
    /**
     * Optional prefilled message. Leave blank to use the Site Settings default.
     */
    whatsappMessage?: string | null;
  };
  secondaryCta?: {
    /**
     * Button or link text.
     */
    label?: string | null;
    type?: ('internal' | 'external' | 'whatsapp') | null;
    /**
     * Path starting with "/" — for example /source-a-fish
     */
    href?: string | null;
    /**
     * Full URL including https://
     */
    url?: string | null;
    /**
     * Optional prefilled message. Leave blank to use the Site Settings default.
     */
    whatsappMessage?: string | null;
  };
  /**
   * Transparent PNG/WebP cutout of a single fish. Shown overlapping the hero shapes.
   */
  fishImage?: (number | null) | Media;
  /**
   * Small hand-note style annotation beside the artwork.
   */
  annotation?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionIntroBlock".
 */
export interface SectionIntroBlock {
  /**
   * Keeps the content but removes the section from the public page.
   */
  hidden?: boolean | null;
  /**
   * Scarlet and Deep Navy are accents. Use them for at most one or two sections per page.
   */
  background?: ('linen' | 'linen-raised' | 'navy' | 'scarlet') | null;
  eyebrow?: string | null;
  heading: string;
  body?: string | null;
  alignment?: ('start' | 'center') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'sectionIntro';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  /**
   * Keeps the content but removes the section from the public page.
   */
  hidden?: boolean | null;
  /**
   * Scarlet and Deep Navy are accents. Use them for at most one or two sections per page.
   */
  background?: ('linen' | 'linen-raised' | 'navy' | 'scarlet') | null;
  width?: ('narrow' | 'wide') | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaCopySplitBlock".
 */
export interface MediaCopySplitBlock {
  /**
   * Keeps the content but removes the section from the public page.
   */
  hidden?: boolean | null;
  /**
   * Scarlet and Deep Navy are accents. Use them for at most one or two sections per page.
   */
  background?: ('linen' | 'linen-raised' | 'navy' | 'scarlet') | null;
  mediaPosition?: ('start' | 'end') | null;
  mediaShape?: ('pool' | 'oval' | 'rect') | null;
  media: number | Media;
  eyebrow?: string | null;
  heading: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  cta?: {
    /**
     * Button or link text.
     */
    label?: string | null;
    type?: ('internal' | 'external' | 'whatsapp') | null;
    /**
     * Path starting with "/" — for example /source-a-fish
     */
    href?: string | null;
    /**
     * Full URL including https://
     */
    url?: string | null;
    /**
     * Optional prefilled message. Leave blank to use the Site Settings default.
     */
    whatsappMessage?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaCopySplit';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessRouteBlock".
 */
export interface ProcessRouteBlock {
  /**
   * Keeps the content but removes the section from the public page.
   */
  hidden?: boolean | null;
  /**
   * Scarlet and Deep Navy are accents. Use them for at most one or two sections per page.
   */
  background?: ('linen' | 'linen-raised' | 'navy' | 'scarlet') | null;
  eyebrow?: string | null;
  /**
   * Numbered steps connected by a current line. Alternates on desktop and stacks into a vertical route on mobile.
   */
  heading: string;
  body?: string | null;
  /**
   * Between two and eight steps. The numbering is generated automatically.
   */
  steps: {
    title: string;
    copy: string;
    id?: string | null;
  }[];
  cta?: {
    /**
     * Button or link text.
     */
    label?: string | null;
    type?: ('internal' | 'external' | 'whatsapp') | null;
    /**
     * Path starting with "/" — for example /source-a-fish
     */
    href?: string | null;
    /**
     * Full URL including https://
     */
    url?: string | null;
    /**
     * Optional prefilled message. Leave blank to use the Site Settings default.
     */
    whatsappMessage?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'processRoute';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CategoryGridBlock".
 */
export interface CategoryGridBlock {
  /**
   * Keeps the content but removes the section from the public page.
   */
  hidden?: boolean | null;
  /**
   * Scarlet and Deep Navy are accents. Use them for at most one or two sections per page.
   */
  background?: ('linen' | 'linen-raised' | 'navy' | 'scarlet') | null;
  eyebrow?: string | null;
  /**
   * Editorial grid of sourcing categories with varied card sizes and controlled overlaps.
   */
  heading: string;
  body?: string | null;
  mode?: ('all' | 'selected') | null;
  /**
   * Order here controls the order on the page.
   */
  categories?: (number | SourcingCategory)[] | null;
  cta?: {
    /**
     * Button or link text.
     */
    label?: string | null;
    type?: ('internal' | 'external' | 'whatsapp') | null;
    /**
     * Path starting with "/" — for example /source-a-fish
     */
    href?: string | null;
    /**
     * Full URL including https://
     */
    url?: string | null;
    /**
     * Optional prefilled message. Leave blank to use the Site Settings default.
     */
    whatsappMessage?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'categoryGrid';
}
/**
 * The kinds of search Finquiry supports. These are never presented as stock — every card carries a "sourced on request" label.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sourcing-categories".
 */
export interface SourcingCategory {
  id: number;
  name: string;
  /**
   * URL path segment. Generated from the title; edit to override.
   */
  slug: string;
  /**
   * One sentence, shown on the category card.
   */
  shortDescription: string;
  longDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverMedia?: (number | null) | Media;
  /**
   * Always signals that this is a search, not stock. Keep wording that makes availability conditional.
   */
  availabilityLabel: string;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Inactive categories are hidden from the site.
   */
  active?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Absolute URL. Only set this when the same content is also published somewhere else.
     */
    canonicalUrl?: string | null;
    /**
     * Adds noindex,nofollow and removes this page from the sitemap.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpecimenRecordBlock".
 */
export interface SpecimenRecordBlock {
  /**
   * Keeps the content but removes the section from the public page.
   */
  hidden?: boolean | null;
  /**
   * Scarlet and Deep Navy are accents. Use them for at most one or two sections per page.
   */
  background?: ('linen' | 'linen-raised' | 'navy' | 'scarlet') | null;
  eyebrow?: string | null;
  /**
   * A collector's specimen sheet. Leave media blank to show a labelled placeholder rather than an invented specimen.
   */
  heading: string;
  body?: string | null;
  /**
   * Small caveat printed under the record.
   */
  note?: string | null;
  mainImage?: (number | null) | Media;
  detailImages?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave a field blank to omit that row. Never enter invented details.
   */
  record?: {
    requestId?: string | null;
    measurement?: string | null;
    origin?: string | null;
    mediaStatus?: ('confirmed' | 'partial' | 'pending') | null;
    notes?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'specimenRecord';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DeliveryStoriesBlock".
 */
export interface DeliveryStoriesBlock {
  /**
   * Keeps the content but removes the section from the public page.
   */
  hidden?: boolean | null;
  /**
   * Scarlet and Deep Navy are accents. Use them for at most one or two sections per page.
   */
  background?: ('linen' | 'linen-raised' | 'navy' | 'scarlet') | null;
  eyebrow?: string | null;
  /**
   * Published delivery records as sourcing postcards. Shows the empty state below until real records are published.
   */
  heading: string;
  body?: string | null;
  mode?: ('featured' | 'selected') | null;
  deliveries?: (number | Delivery)[] | null;
  limit?: number | null;
  /**
   * Shown when no delivery record is published yet.
   */
  emptyState?: {
    heading?: string | null;
    body?: string | null;
    behaviour?: ('show' | 'hide') | null;
  };
  cta?: {
    /**
     * Button or link text.
     */
    label?: string | null;
    type?: ('internal' | 'external' | 'whatsapp') | null;
    /**
     * Path starting with "/" — for example /source-a-fish
     */
    href?: string | null;
    /**
     * Full URL including https://
     */
    url?: string | null;
    /**
     * Optional prefilled message. Leave blank to use the Site Settings default.
     */
    whatsappMessage?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'deliveryStories';
}
/**
 * Real, documented deliveries. Never publish private customer details, full addresses or internal vendor names.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deliveries".
 */
export interface Delivery {
  id: number;
  title: string;
  /**
   * The Request ID shown publicly, e.g. FQ-2609-0001. Safe to display — it identifies the search, not the customer.
   */
  requestId?: string | null;
  /**
   * What the collector originally asked for, in their terms.
   */
  requirement: string;
  specimen: string;
  /**
   * Used by the filters on the Deliveries index.
   */
  category?: (number | null) | SourcingCategory;
  variety?: string | null;
  approximateSize?: string | null;
  /**
   * City or state only — never a full address.
   */
  origin: string;
  /**
   * City or state only — never a full address.
   */
  destination: string;
  outcome?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  mainImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Packing and dispatch documentation.
   */
  packingMedia?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The customer’s own words. Leave blank unless you hold written permission.
   */
  testimonial?: string | null;
  /**
   * Display name and city, e.g. "R.K., Pune".
   */
  testimonialAttribution?: string | null;
  testimonialConsent?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Absolute URL. Only set this when the same content is also published somewhere else.
     */
    canonicalUrl?: string | null;
    /**
     * Adds noindex,nofollow and removes this page from the sitemap.
     */
    noIndex?: boolean | null;
  };
  /**
   * URL path segment. Generated from the title; edit to override.
   */
  slug: string;
  deliveryDate: string;
  /**
   * Featured stories can appear on the homepage.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AquariumFeatureBlock".
 */
export interface AquariumFeatureBlock {
  /**
   * Keeps the content but removes the section from the public page.
   */
  hidden?: boolean | null;
  eyebrow?: string | null;
  heading: string;
  body?: string | null;
  mainImage?: (number | null) | Media;
  detailImages?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  services?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  cta?: {
    /**
     * Button or link text.
     */
    label?: string | null;
    type?: ('internal' | 'external' | 'whatsapp') | null;
    /**
     * Path starting with "/" — for example /source-a-fish
     */
    href?: string | null;
    /**
     * Full URL including https://
     */
    url?: string | null;
    /**
     * Optional prefilled message. Leave blank to use the Site Settings default.
     */
    whatsappMessage?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'aquariumFeature';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageGalleryBlock".
 */
export interface ImageGalleryBlock {
  /**
   * Keeps the content but removes the section from the public page.
   */
  hidden?: boolean | null;
  /**
   * Scarlet and Deep Navy are accents. Use them for at most one or two sections per page.
   */
  background?: ('linen' | 'linen-raised' | 'navy' | 'scarlet') | null;
  heading?: string | null;
  images: {
    image: number | Media;
    caption?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageGallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock".
 */
export interface VideoBlock {
  /**
   * Keeps the content but removes the section from the public page.
   */
  hidden?: boolean | null;
  /**
   * Scarlet and Deep Navy are accents. Use them for at most one or two sections per page.
   */
  background?: ('linen' | 'linen-raised' | 'navy' | 'scarlet') | null;
  heading?: string | null;
  source?: ('upload' | 'external') | null;
  file?: (number | null) | Media;
  /**
   * YouTube or Vimeo watch/embed URL.
   */
  url?: string | null;
  /**
   * Required for uploaded video so the player never loads blank.
   */
  poster?: (number | null) | Media;
  /**
   * WebVTT captions file. Required for video that carries meaning.
   */
  captionsTrack?: (number | null) | Media;
  /**
   * Text alternative for the video.
   */
  transcript?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'video';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TrustStatementsBlock".
 */
export interface TrustStatementsBlock {
  /**
   * Keeps the content but removes the section from the public page.
   */
  hidden?: boolean | null;
  /**
   * Scarlet and Deep Navy are accents. Use them for at most one or two sections per page.
   */
  background?: ('linen' | 'linen-raised' | 'navy' | 'scarlet') | null;
  eyebrow?: string | null;
  /**
   * Three strong editorial ideas plus smaller proof points.
   */
  heading: string;
  /**
   * Three reads best. More than four weakens the hierarchy.
   */
  statements: {
    heading: string;
    copy: string;
    id?: string | null;
  }[];
  proofPoints?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'trustStatements';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedArticlesBlock".
 */
export interface FeaturedArticlesBlock {
  /**
   * Keeps the content but removes the section from the public page.
   */
  hidden?: boolean | null;
  /**
   * Scarlet and Deep Navy are accents. Use them for at most one or two sections per page.
   */
  background?: ('linen' | 'linen-raised' | 'navy' | 'scarlet') | null;
  eyebrow?: string | null;
  /**
   * Magazine shelf: one lead article plus supporting ones.
   */
  heading: string;
  body?: string | null;
  mode?: ('latest' | 'selected') | null;
  posts?: (number | Post)[] | null;
  limit?: number | null;
  /**
   * Shown while no article is published yet — for example on a new site where every article is still a draft.
   */
  emptyState?: {
    heading?: string | null;
    body?: string | null;
    behaviour?: ('show' | 'hide') | null;
  };
  cta?: {
    /**
     * Button or link text.
     */
    label?: string | null;
    type?: ('internal' | 'external' | 'whatsapp') | null;
    /**
     * Path starting with "/" — for example /source-a-fish
     */
    href?: string | null;
    /**
     * Full URL including https://
     */
    url?: string | null;
    /**
     * Optional prefilled message. Leave blank to use the Site Settings default.
     */
    whatsappMessage?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuredArticles';
}
/**
 * Knowledge Hub articles.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * One or two sentences. Used on cards and as the SEO fallback.
   */
  excerpt: string;
  featuredImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Leave blank to fall back to the newest articles in the same category.
   */
  relatedPosts?: (number | Post)[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Absolute URL. Only set this when the same content is also published somewhere else.
     */
    canonicalUrl?: string | null;
    /**
     * Adds noindex,nofollow and removes this page from the sitemap.
     */
    noIndex?: boolean | null;
  };
  /**
   * URL path segment. Generated from the title; edit to override.
   */
  slug: string;
  category: number | Category;
  tags?: string[] | null;
  author?: (number | null) | Author;
  /**
   * Set automatically on first publish. Edit to backdate.
   */
  publishedAt?: string | null;
  /**
   * Minutes, calculated from the article body on save.
   */
  readingTime?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * URL path segment. Generated from the title; edit to override.
   */
  slug: string;
  description?: string | null;
  /**
   * Optional. Leave blank for a top-level category.
   */
  parent?: (number | null) | Category;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * URL path segment. Generated from the title; edit to override.
   */
  slug: string;
  title?: string | null;
  bio?: string | null;
  photo?: (number | null) | Media;
  social?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqsBlock".
 */
export interface FaqsBlock {
  /**
   * Keeps the content but removes the section from the public page.
   */
  hidden?: boolean | null;
  /**
   * Scarlet and Deep Navy are accents. Use them for at most one or two sections per page.
   */
  background?: ('linen' | 'linen-raised' | 'navy' | 'scarlet') | null;
  eyebrow?: string | null;
  heading: string;
  mode?: ('category' | 'selected') | null;
  category?: ('sourcing' | 'delivery' | 'pricing' | 'aquariums' | 'general') | null;
  faqs?: (number | Faq)[] | null;
  /**
   * Only enable where these exact questions and answers are visible on the page — Google requires the rendered content to match.
   */
  emitStructuredData?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faqs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category: 'sourcing' | 'delivery' | 'pricing' | 'aquariums' | 'general';
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Only published records appear on the public site.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock".
 */
export interface CtaBlock {
  /**
   * Keeps the content but removes the section from the public page.
   */
  hidden?: boolean | null;
  /**
   * Scarlet and Deep Navy are accents. Use them for at most one or two sections per page.
   */
  background?: ('linen' | 'linen-raised' | 'navy' | 'scarlet') | null;
  eyebrow?: string | null;
  heading: string;
  body?: string | null;
  primaryCta?: {
    /**
     * Button or link text.
     */
    label?: string | null;
    type?: ('internal' | 'external' | 'whatsapp') | null;
    /**
     * Path starting with "/" — for example /source-a-fish
     */
    href?: string | null;
    /**
     * Full URL including https://
     */
    url?: string | null;
    /**
     * Optional prefilled message. Leave blank to use the Site Settings default.
     */
    whatsappMessage?: string | null;
  };
  secondaryCta?: {
    /**
     * Button or link text.
     */
    label?: string | null;
    type?: ('internal' | 'external' | 'whatsapp') | null;
    /**
     * Path starting with "/" — for example /source-a-fish
     */
    href?: string | null;
    /**
     * Full URL including https://
     */
    url?: string | null;
    /**
     * Optional prefilled message. Leave blank to use the Site Settings default.
     */
    whatsappMessage?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aquarium-projects".
 */
export interface AquariumProject {
  id: number;
  title: string;
  summary: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverMedia?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Absolute URL. Only set this when the same content is also published somewhere else.
     */
    canonicalUrl?: string | null;
    /**
     * Adds noindex,nofollow and removes this page from the sitemap.
     */
    noIndex?: boolean | null;
  };
  /**
   * URL path segment. Generated from the title; edit to override.
   */
  slug: string;
  serviceType: 'service' | 'project';
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Only real, approved quotes. Nothing here is ever seeded or invented.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * How the customer agreed to be credited, e.g. "R.K." or a first name.
   */
  displayName: string;
  city?: string | null;
  quote: string;
  /**
   * Optional. Links this quote to a published delivery story.
   */
  relatedDelivery?: (number | null) | Delivery;
  consent?: boolean | null;
  /**
   * Only published records appear on the public site.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer sourcing requests. Private — never exposed on the public site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  requestId: string;
  status: 'new' | 'reviewing' | 'sourcing' | 'options-shared' | 'approved' | 'closed' | 'unsuccessful';
  assignedTo?: (number | null) | User;
  fullName: string;
  whatsapp: string;
  email?: string | null;
  city: string;
  state: string;
  pincode: string;
  fishRequired: string;
  species?: string | null;
  variety?: string | null;
  preferredSize?: string | null;
  sizeRange?: string | null;
  quantity?: number | null;
  alternativesAccepted?: ('yes' | 'no' | 'describe') | null;
  alternativesNotes?: string | null;
  tankDimensions?: string | null;
  waterVolume?: string | null;
  tankInhabitants?: string | null;
  tankCycled?: ('yes' | 'no' | 'unsure' | 'new-system') | null;
  systemNotes?: string | null;
  budgetRange?: string | null;
  timeline?: string | null;
  deliveryCity?: string | null;
  deliveryPincode?: string | null;
  additionalRequirements?: string | null;
  preferredContactTime?: string | null;
  /**
   * Customer-supplied reference. Stored privately.
   */
  referenceImage?: (number | null) | PrivateMedia;
  /**
   * Never shown to the customer.
   */
  internalNotes?: string | null;
  meta?: {
    sourcePage?: string | null;
    /**
     * Idempotency key minted by the browser for one filled-in form. A retry or a double click carries the same value, so the second arrival is recognised instead of creating a duplicate enquiry.
     */
    submissionToken?: string | null;
    consentAt?: string | null;
    /**
     * The exact wording the customer agreed to.
     */
    consentText?: string | null;
    utm?: {
      source?: string | null;
      medium?: string | null;
      campaign?: string | null;
      term?: string | null;
      content?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Staff accounts for the Finquiry admin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Super Admin: everything. Admin: content, media and non-super-admin users. Editor: content only.
   */
  role: 'super-admin' | 'admin' | 'editor';
  /**
   * When off, this editor can save drafts but cannot publish them.
   */
  canPublish?: boolean | null;
  /**
   * Deactivated accounts keep their history but lose all access.
   */
  active?: boolean | null;
  lastLogin?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Customer reference images. Private — never rendered on the public site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "private-media".
 */
export interface PrivateMedia {
  id: number;
  /**
   * Request ID this upload belongs to.
   */
  enquiryRequestId?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    preview?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Old paths that should forward somewhere new.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'sourcing-categories';
        value: number | SourcingCategory;
      } | null)
    | ({
        relationTo: 'deliveries';
        value: number | Delivery;
      } | null)
    | ({
        relationTo: 'aquarium-projects';
        value: number | AquariumProject;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'private-media';
        value: number | PrivateMedia;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  pageType?: T;
  legalReviewRequired?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        intro?: T;
        image?: T;
      };
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        sectionIntro?: T | SectionIntroBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        mediaCopySplit?: T | MediaCopySplitBlockSelect<T>;
        processRoute?: T | ProcessRouteBlockSelect<T>;
        categoryGrid?: T | CategoryGridBlockSelect<T>;
        specimenRecord?: T | SpecimenRecordBlockSelect<T>;
        deliveryStories?: T | DeliveryStoriesBlockSelect<T>;
        aquariumFeature?: T | AquariumFeatureBlockSelect<T>;
        imageGallery?: T | ImageGalleryBlockSelect<T>;
        video?: T | VideoBlockSelect<T>;
        trustStatements?: T | TrustStatementsBlockSelect<T>;
        featuredArticles?: T | FeaturedArticlesBlockSelect<T>;
        faqs?: T | FaqsBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  slug?: T;
  showInNavigation?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  hidden?: T;
  eyebrow?: T;
  headline?: T;
  body?: T;
  trustLine?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        type?: T;
        href?: T;
        url?: T;
        whatsappMessage?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        type?: T;
        href?: T;
        url?: T;
        whatsappMessage?: T;
      };
  fishImage?: T;
  annotation?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionIntroBlock_select".
 */
export interface SectionIntroBlockSelect<T extends boolean = true> {
  hidden?: T;
  background?: T;
  eyebrow?: T;
  heading?: T;
  body?: T;
  alignment?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  hidden?: T;
  background?: T;
  width?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaCopySplitBlock_select".
 */
export interface MediaCopySplitBlockSelect<T extends boolean = true> {
  hidden?: T;
  background?: T;
  mediaPosition?: T;
  mediaShape?: T;
  media?: T;
  eyebrow?: T;
  heading?: T;
  content?: T;
  cta?:
    | T
    | {
        label?: T;
        type?: T;
        href?: T;
        url?: T;
        whatsappMessage?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessRouteBlock_select".
 */
export interface ProcessRouteBlockSelect<T extends boolean = true> {
  hidden?: T;
  background?: T;
  eyebrow?: T;
  heading?: T;
  body?: T;
  steps?:
    | T
    | {
        title?: T;
        copy?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        type?: T;
        href?: T;
        url?: T;
        whatsappMessage?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CategoryGridBlock_select".
 */
export interface CategoryGridBlockSelect<T extends boolean = true> {
  hidden?: T;
  background?: T;
  eyebrow?: T;
  heading?: T;
  body?: T;
  mode?: T;
  categories?: T;
  cta?:
    | T
    | {
        label?: T;
        type?: T;
        href?: T;
        url?: T;
        whatsappMessage?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpecimenRecordBlock_select".
 */
export interface SpecimenRecordBlockSelect<T extends boolean = true> {
  hidden?: T;
  background?: T;
  eyebrow?: T;
  heading?: T;
  body?: T;
  note?: T;
  mainImage?: T;
  detailImages?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  record?:
    | T
    | {
        requestId?: T;
        measurement?: T;
        origin?: T;
        mediaStatus?: T;
        notes?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DeliveryStoriesBlock_select".
 */
export interface DeliveryStoriesBlockSelect<T extends boolean = true> {
  hidden?: T;
  background?: T;
  eyebrow?: T;
  heading?: T;
  body?: T;
  mode?: T;
  deliveries?: T;
  limit?: T;
  emptyState?:
    | T
    | {
        heading?: T;
        body?: T;
        behaviour?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        type?: T;
        href?: T;
        url?: T;
        whatsappMessage?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AquariumFeatureBlock_select".
 */
export interface AquariumFeatureBlockSelect<T extends boolean = true> {
  hidden?: T;
  eyebrow?: T;
  heading?: T;
  body?: T;
  mainImage?: T;
  detailImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  services?:
    | T
    | {
        label?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        type?: T;
        href?: T;
        url?: T;
        whatsappMessage?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageGalleryBlock_select".
 */
export interface ImageGalleryBlockSelect<T extends boolean = true> {
  hidden?: T;
  background?: T;
  heading?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock_select".
 */
export interface VideoBlockSelect<T extends boolean = true> {
  hidden?: T;
  background?: T;
  heading?: T;
  source?: T;
  file?: T;
  url?: T;
  poster?: T;
  captionsTrack?: T;
  transcript?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TrustStatementsBlock_select".
 */
export interface TrustStatementsBlockSelect<T extends boolean = true> {
  hidden?: T;
  background?: T;
  eyebrow?: T;
  heading?: T;
  statements?:
    | T
    | {
        heading?: T;
        copy?: T;
        id?: T;
      };
  proofPoints?:
    | T
    | {
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedArticlesBlock_select".
 */
export interface FeaturedArticlesBlockSelect<T extends boolean = true> {
  hidden?: T;
  background?: T;
  eyebrow?: T;
  heading?: T;
  body?: T;
  mode?: T;
  posts?: T;
  limit?: T;
  emptyState?:
    | T
    | {
        heading?: T;
        body?: T;
        behaviour?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        type?: T;
        href?: T;
        url?: T;
        whatsappMessage?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqsBlock_select".
 */
export interface FaqsBlockSelect<T extends boolean = true> {
  hidden?: T;
  background?: T;
  eyebrow?: T;
  heading?: T;
  mode?: T;
  category?: T;
  faqs?: T;
  emitStructuredData?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock_select".
 */
export interface CtaBlockSelect<T extends boolean = true> {
  hidden?: T;
  background?: T;
  eyebrow?: T;
  heading?: T;
  body?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        type?: T;
        href?: T;
        url?: T;
        whatsappMessage?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        type?: T;
        href?: T;
        url?: T;
        whatsappMessage?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  featuredImage?: T;
  content?: T;
  relatedPosts?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  slug?: T;
  category?: T;
  tags?: T;
  author?: T;
  publishedAt?: T;
  readingTime?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  parent?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  title?: T;
  bio?: T;
  photo?: T;
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sourcing-categories_select".
 */
export interface SourcingCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  shortDescription?: T;
  longDescription?: T;
  coverMedia?: T;
  availabilityLabel?: T;
  order?: T;
  active?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deliveries_select".
 */
export interface DeliveriesSelect<T extends boolean = true> {
  title?: T;
  requestId?: T;
  requirement?: T;
  specimen?: T;
  category?: T;
  variety?: T;
  approximateSize?: T;
  origin?: T;
  destination?: T;
  outcome?: T;
  mainImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  packingMedia?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  testimonial?: T;
  testimonialAttribution?: T;
  testimonialConsent?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  slug?: T;
  deliveryDate?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aquarium-projects_select".
 */
export interface AquariumProjectsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  content?: T;
  coverMedia?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  slug?: T;
  serviceType?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  displayName?: T;
  city?: T;
  quote?: T;
  relatedDelivery?: T;
  consent?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  requestId?: T;
  status?: T;
  assignedTo?: T;
  fullName?: T;
  whatsapp?: T;
  email?: T;
  city?: T;
  state?: T;
  pincode?: T;
  fishRequired?: T;
  species?: T;
  variety?: T;
  preferredSize?: T;
  sizeRange?: T;
  quantity?: T;
  alternativesAccepted?: T;
  alternativesNotes?: T;
  tankDimensions?: T;
  waterVolume?: T;
  tankInhabitants?: T;
  tankCycled?: T;
  systemNotes?: T;
  budgetRange?: T;
  timeline?: T;
  deliveryCity?: T;
  deliveryPincode?: T;
  additionalRequirements?: T;
  preferredContactTime?: T;
  referenceImage?: T;
  internalNotes?: T;
  meta?:
    | T
    | {
        sourcePage?: T;
        submissionToken?: T;
        consentAt?: T;
        consentText?: T;
        utm?:
          | T
          | {
              source?: T;
              medium?: T;
              campaign?: T;
              term?: T;
              content?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  decorative?: T;
  alt?: T;
  caption?: T;
  credit?: T;
  tags?: T;
  seedKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        desktop?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        social?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "private-media_select".
 */
export interface PrivateMediaSelect<T extends boolean = true> {
  enquiryRequestId?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        preview?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  canPublish?: T;
  active?: T;
  lastLogin?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Edit every homepage section here. Drag sections to reorder them; each one can be hidden without deleting its content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero: {
    eyebrow?: string | null;
    /**
     * Wrap a word or phrase in *asterisks* to set it in Scarlet, e.g. Every Collector Is *Searching* for Something.
     */
    headline: string;
    body?: string | null;
    trustLine?: string | null;
    primaryCta?: {
      /**
       * Button or link text.
       */
      label?: string | null;
      type?: ('internal' | 'external' | 'whatsapp') | null;
      /**
       * Path starting with "/" — for example /source-a-fish
       */
      href?: string | null;
      /**
       * Full URL including https://
       */
      url?: string | null;
      /**
       * Optional prefilled message. Leave blank to use the Site Settings default.
       */
      whatsappMessage?: string | null;
    };
    secondaryCta?: {
      /**
       * Button or link text.
       */
      label?: string | null;
      type?: ('internal' | 'external' | 'whatsapp') | null;
      /**
       * Path starting with "/" — for example /source-a-fish
       */
      href?: string | null;
      /**
       * Full URL including https://
       */
      url?: string | null;
      /**
       * Optional prefilled message. Leave blank to use the Site Settings default.
       */
      whatsappMessage?: string | null;
    };
    /**
     * Transparent cutout of one fish (PNG or WebP). It overlaps the hero shapes and drifts gently. Replace this to change the hero artwork.
     */
    fishImage?: (number | null) | Media;
    /**
     * Small annotation printed beside the artwork.
     */
    annotation?: string | null;
    scrollHint?: string | null;
  };
  /**
   * The homepage body. Drag to reorder, use "Hide this section" to take one off the page, and click Add to bring in a new section.
   */
  sections?:
    | (
        | SectionIntroBlock
        | ProcessRouteBlock
        | CategoryGridBlock
        | SpecimenRecordBlock
        | TrustStatementsBlock
        | DeliveryStoriesBlock
        | AquariumFeatureBlock
        | FeaturedArticlesBlock
        | FaqsBlock
        | MediaCopySplitBlock
        | RichTextBlock
        | ImageGalleryBlock
        | VideoBlock
        | CtaBlock
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Absolute URL. Only set this when the same content is also published somewhere else.
     */
    canonicalUrl?: string | null;
    /**
     * Adds noindex,nofollow and removes this page from the sitemap.
     */
    noIndex?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Brand, contact details and defaults used across every page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brandName: string;
  tagline?: string | null;
  shortDescription?: string | null;
  logo?: (number | null) | Media;
  logoOnDark?: (number | null) | Media;
  favicon?: (number | null) | Media;
  contactEmail?: string | null;
  /**
   * International format, digits only, no "+" or spaces. Example: 919876543210
   */
  whatsappNumber?: string | null;
  /**
   * Prefilled into WhatsApp when someone taps a WhatsApp link.
   */
  whatsappDefaultMessage?: string | null;
  phone?: string | null;
  address?: {
    line1?: string | null;
    line2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  socialLinks?:
    | {
        platform: 'instagram' | 'facebook' | 'youtube' | 'x' | 'whatsapp';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The last fallback. A page uses its own SEO override first, then its title and excerpt, then these values.
   */
  defaultSeo?: {
    titleTemplate?: string | null;
    defaultTitle?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  /**
   * Used to build the Organisation structured data.
   */
  organisation?: {
    legalName?: string | null;
    foundingYear?: number | null;
    areaServed?: string | null;
    /**
     * Profile URLs used to confirm identity.
     */
    sameAs?: string[] | null;
  };
  /**
   * Provider-agnostic. Environment variables take precedence when both are set.
   */
  analytics?: {
    provider?: ('none' | 'plausible' | 'umami' | 'ga4') | null;
    measurementId?: string | null;
    scriptUrl?: string | null;
  };
  consent?: {
    enabled?: boolean | null;
    message?: string | null;
    policyLink?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Primary navigation, header CTA and announcement bar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * Drag to reorder. Keep labels short — more than eight items crowds the desktop bar.
   */
  navItems?:
    | {
        label: string;
        /**
         * Path starting with "/", e.g. /how-it-works
         */
        href: string;
        /**
         * Optional. Shown under the label in the mobile menu.
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    /**
     * Button or link text.
     */
    label?: string | null;
    type?: ('internal' | 'external' | 'whatsapp') | null;
    /**
     * Path starting with "/" — for example /source-a-fish
     */
    href?: string | null;
    /**
     * Full URL including https://
     */
    url?: string | null;
    /**
     * Optional prefilled message. Leave blank to use the Site Settings default.
     */
    whatsappMessage?: string | null;
  };
  announcement?: {
    enabled?: boolean | null;
    text?: string | null;
    href?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Two sentences at most, shown beside the logo.
   */
  brandStatement?: string | null;
  navGroups?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown in the small print row at the bottom.
   */
  policyLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Pulls the email, WhatsApp number and address from Site Settings.
   */
  showContactDetails?: boolean | null;
  /**
   * Use {year} and {brand} as placeholders.
   */
  copyrightFormat?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        body?: T;
        trustLine?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              type?: T;
              href?: T;
              url?: T;
              whatsappMessage?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              type?: T;
              href?: T;
              url?: T;
              whatsappMessage?: T;
            };
        fishImage?: T;
        annotation?: T;
        scrollHint?: T;
      };
  sections?:
    | T
    | {
        sectionIntro?: T | SectionIntroBlockSelect<T>;
        processRoute?: T | ProcessRouteBlockSelect<T>;
        categoryGrid?: T | CategoryGridBlockSelect<T>;
        specimenRecord?: T | SpecimenRecordBlockSelect<T>;
        trustStatements?: T | TrustStatementsBlockSelect<T>;
        deliveryStories?: T | DeliveryStoriesBlockSelect<T>;
        aquariumFeature?: T | AquariumFeatureBlockSelect<T>;
        featuredArticles?: T | FeaturedArticlesBlockSelect<T>;
        faqs?: T | FaqsBlockSelect<T>;
        mediaCopySplit?: T | MediaCopySplitBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        imageGallery?: T | ImageGalleryBlockSelect<T>;
        video?: T | VideoBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  tagline?: T;
  shortDescription?: T;
  logo?: T;
  logoOnDark?: T;
  favicon?: T;
  contactEmail?: T;
  whatsappNumber?: T;
  whatsappDefaultMessage?: T;
  phone?: T;
  address?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  defaultSeo?:
    | T
    | {
        titleTemplate?: T;
        defaultTitle?: T;
        description?: T;
        image?: T;
      };
  organisation?:
    | T
    | {
        legalName?: T;
        foundingYear?: T;
        areaServed?: T;
        sameAs?: T;
      };
  analytics?:
    | T
    | {
        provider?: T;
        measurementId?: T;
        scriptUrl?: T;
      };
  consent?:
    | T
    | {
        enabled?: T;
        message?: T;
        policyLink?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        description?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        type?: T;
        href?: T;
        url?: T;
        whatsappMessage?: T;
      };
  announcement?:
    | T
    | {
        enabled?: T;
        text?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  brandStatement?: T;
  navGroups?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  policyLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  showContactDetails?: T;
  copyrightFormat?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}